# Any version string with `GIT_*` variables will break Conda rendering.
# That's the reason behind this "dummy" version string.
#
# Use `conda-build-prepare` before building for some reasonable version string.
{% set version = 'v0.0_X_gUNKNOWN' %}
{% set boost_version = "1.73.*" %}
{% set python_version = PYTHON_VERSION | default('3.7') %}
{% set py_suffix = 'py%s'|format(python_version|replace('.', '')) %}

package:
  name: nextpnr-xilinx
  version: {{ version }}

source:
  git_url: https://github.com/daveshah1/nextpnr-xilinx.git
  git_rev: xilinx-upstream

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}_{{ py_suffix }}
  script_env:
    - CI
    - USE_PYPY

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python_version }}
    - libboost {{ boost_version }}
    - py-boost {{ boost_version }}
    - make
  host:
    - bison
    - boost {{ boost_version }}
    - cmake
    - eigen
    - flex
    - fontconfig
    - pkg-config
    - python {{ python_version }}
    - libboost {{ boost_version }}
    - py-boost {{ boost_version }}
  run:
    - libboost {{ boost_version }}
    - py-boost {{ boost_version }}
    - python {{ python_version }}

test:
  commands:
    - nextpnr-xilinx -V

about:
  home: https://github.com/daveshah1/nextpnr-xilinx.git
  license: ISC
  license_file: COPYING
  summary: 'nextpnr aims to be a vendor neutral, timing driven, FOSS FPGA place and route tool.'
